kind: pipeline
type: docker
name: default

platform:
  os: linux

steps:
- name: build
  image: docker
  environment:
    DOCKER_USERNAME:
      from_secret: repo_username
    DOCKER_PASSWORD:
      from_secret: repo_password
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker login docker.decryptology.net -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t docker.decryptology.net/decryptology/browserlessbot:latest .
  - docker push docker.decryptology.net/decryptology/browserlessbot:latest

steps:
- name: deploy
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker run --rm --name:update_browserlessbot -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower:latest --run-once --cleanup --rolling-restart browserlessbot
  - docker wait update_browserlessbot

